Homework 7

Imagine you are an Engineer for Amazon Alexa.  You are given the task of understanding text input and classifying it.  Create a data set of sayings that fall into 2 Categories: Getting Directions and Playing Music.  Make sure you data set has at least 100 examples total.

Example Playing Music:
"Play some Pantera on Spotify"

Example Directions:
"Where is the nearest Starbucks"

In [0]:
music =[
    "play rock music on pandora",
    "play, beatles",
    "play 60s music",
    "play relaxing music",
    "play holiday music on all devices",
    "play my playlist on Spotify",
    "play z100 on iHeartRadio",
    "play classic rock hits on TuneIn",
    "play some music"
    "play folk music in Amazon at volume 6",
    "play jazz music for working",
    "play firework by Ketty Perry",
    "play Star 102 from iHeart Radio",
    "play next music",
    "play previous music",
    "play Wonderland station from SiriusXM",
    "play some Prime Music",
    "play my dinner party playlist",
    "play the album abbey road from the Beatles on Spotify",
    "play My Radio",
    "play wonderwall from Oasis on repeat",
    "play Adele station on pandora",
    "play Today’s Hits on Spotify",
    "play the United States national anthem",
    "play In The End by Linkin Park",
    "play some dance music in the Living Room",
    "play my parents playlist",
    "play my brothers playlist on pandora",
    "play Christmas carols",
    "play Frank Sinatra",
    "play the last song I was listening to",
    "play the Mellow '70s Gold playlist from Amazon Music",
    "play sounds of the jungle",
    "play music for reading",
    "play something i havent heard in a while",
    "play outlaw country on pandora",
    "play that song again",
    "play some songs for sleeping",
    "play the song of the day",
    "play the song that goes: Head out on the highway",
    "play music for taking a bath",
    "play music to cheer me up",
    "play the latest Linkin Park album",
    "stop playing in 30 minutes",
    "play my Miles Davis station",
    "play the new Bruno Mars song",
    "play star 101.3 on iHeartRadio",
    "play music for a road trip",
    "play a song from my Apple Music playlist",
    "play me something relaxing",
    "play stressed out by twenty one pilots"
]

In [0]:
directions =[
    "Where is the nearest mcdonalds",
    "how do i get to starbucks",
    "how far a drive to orlando"
    "where is the nearest gas station",
    "how do you get to maple drive",
    "what are the directions to the airport",
    "how do i get the train station",
    "how do i get the gym",
    "where is oak forest neighborhood",
    "where is dairy queen is the closest",
    "which way to the cocoa beach",
    "how do i get to the nearest mexican food",
    "how do i get to my gym with a bicycle",
    "are their any veteranarians nearby",
    "which way to the hospital",
    "where is the closest park",
    "how do i get to the grocery store",
    "how far is the drive to doctor",
    "where is the best rated mexican restaurant",
    "how far to disney by amtrak train",
    "where is the nearest burger king",
    "which cvs store is the closest",
    "which way to the best buy",
    "how far is the walking trail",
    "where is the closest doctors within 5 miles",
    "find the closest movie theater",
    "which way to the top rated thai restaurant",
    "which way is the zoo",
    "how to get to downtown",
    "how far to drive to the dentist",
    "where is the best rated school closest to me",
    "What are the directions to the mall",
    "What is the way home",
    "Get me directions to the gas station",
    "where is the nearest gas station",
    "how far to the park",
    "what is the closest restaurant",
    "where is the closest pharmacy",
    "which way to the stadium",
    "where is the nearest home depot ",
    "how far to work",
    "where is the closest library located",
    "how do i get to the library",
    "how far a drive to miami",
    "where is the nearest starbucks",
    "which mcondalds is the nearest",
    "which is closer mcdonalds or burger king",
    "which way to the lake",
    "how to get to airport",
    "where is closest bus station",
    "how do it get to the bus station"
]



In [4]:
print(f'Length of Music is {len(music)}, Length of Directions is {len(directions)}')

Length of Music is 50, Length of Directions is 50


Q1 Given the following module that outputs a vector which represents your input sentence, transform your data into numbers.

In [5]:
import tensorflow as tf
import tensorflow_hub as hub

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/3")
musicEmbeddings = embed(music)["outputs"]
directionEmbeddings = embed(directions)["outputs"]

print(musicEmbeddings)

tf.Tensor(
[[ 0.01492012  0.02582433  0.08476008 ... -0.01204567 -0.01502339
  -0.02175183]
 [-0.00135757  0.0017423   0.08162555 ... -0.00012654 -0.00583726
   0.03420949]
 [ 0.01468289  0.02749554  0.08986668 ... -0.04574937 -0.03441996
   0.07641818]
 ...
 [-0.00100115  0.00360921  0.08328559 ...  0.01046749 -0.06933691
   0.0568288 ]
 [-0.03438263 -0.02549896  0.09147818 ... -0.01722317  0.02044252
  -0.00858754]
 [ 0.00650887  0.02147421  0.09309313 ... -0.00640677 -0.0690588
   0.04912144]], shape=(50, 512), dtype=float32)


In [6]:
musicEmbeddings.shape

TensorShape([50, 512])

Q2: Take your numbers from Q1 and create 2 classifiers of any type.  What is your best guess for the accuracy of your models. (Don't forget to use good data science practices!)

In [0]:
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [0]:
music_array = np.array(musicEmbeddings)
direction_array = np.array(directionEmbeddings)

In [0]:
import pandas as pd

musicDF = pd.DataFrame(music_array)
directionDF = pd.DataFrame(direction_array)

In [0]:
#Labels 1 for music and 0 for directions
musicDF.insert(512, "Class", 1)
directionDF.insert(512, "Class", 0)

In [0]:
final_data = pd.concat([musicDF, directionDF], ignore_index= True)

In [0]:
# Set variables for X and y
X = final_data.drop('Class', axis=1)
y = final_data['Class']

In [0]:
# Define train test splits 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [16]:
from sklearn.svm import SVC
svc_classifier = SVC(kernel='linear')

# Fit the SVM model
svc_classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
# Run the predictions for the SVM
y_pred_svc = svc_classifier.predict(X_test)

In [0]:
# Import model evaluation packages
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

In [19]:
# Print results for the SVM
print("The accuracy of the SVM model is:",metrics.accuracy_score(y_test, y_pred_svc))
print(confusion_matrix(y_test,y_pred_svc))
print(classification_report(y_test,y_pred_svc))

The accuracy of the SVM model is: 1.0
[[13  0]
 [ 0  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         7

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [20]:
# Import the random forest model
from sklearn.ensemble import RandomForestClassifier

random_forest_classifier = RandomForestClassifier(n_estimators=100)
# Train the model 
random_forest_classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
y_pred_rf = random_forest_classifier.predict(X_test)

In [22]:
# Print the results of the random forest model 
print("The accuracy of the random forest model is:",metrics.accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))

The accuracy of the random forest model is: 1.0
[[13  0]
 [ 0  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         7

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



#### Both random forest model and SVM classifier performed at an accuracy of 100%. I think it was easy to classify since play is used all the time in music and never in the directions. 